### ISSUE TITLE
Arduino Nano Not working 

### ISSUE THREAD

**Issue by manisaranbala** [iliasam/Laser_tape_reverse_engineering#10]
My device U85B .Nano RX TX connect not reading.but TTL good reading .we need Arduino Nano or 2560 program connect Desktop.it is possible?

**Comment by iliasam** [comment]
Sorry, I don't understand your question.
Can you describe step by step what you already tried?
What hardware do you have?

**Comment by manisaranbala** [comment]
![2023-11-08_04h47_28](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/fb469fe6-624a-444d-b02e-ef9c5e1a6044)
my device 40m 85B TTL MODE Reading good. but not reading Arduino Nano  serial communication

**Comment by manisaranbala** [comment]
https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/c912efa5-3983-4914-af42-9ec90e0fe0e4

laser light power is down in few minutes. and also the reading is differ so how can solve it

**Comment by manisaranbala** [comment]
set volt 2.2 and 3 and 3.2 same Problems

**Comment by manisaranbala** [comment]
https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/d4dd4189-3ae5-41b0-8331-4e6f3562143d

**Comment by manisaranbala** [comment]
[Result_2023-11-14 12-49-20.csv](https://github.com/iliasam/Laser_tape_reverse_engineering/files/13345703/Result_2023-11-14.12-49-20.csv)

**Comment by iliasam** [comment]
Do you have this problem with USB-UART converter?
Also, try to disconnect RX line of U85B module - maybe 5V from Arduino is bad for U85B.

**Comment by manisaranbala** [comment]
internal battery (AAA)same problem. Need continue Data Reading possible?

**Comment by manisaranbala** [comment]
![WhatsApp Image 2023-11-14 at 4 13 26 PM](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/e382d617-ade8-48de-9a24-08f7acc15996)
![WhatsApp Image 2023-11-14 at 4 13 26 PM (1)](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/c56786a8-c3ce-4fcf-8eeb-8230bb3d34bb)
![WhatsApp Image 2023-11-14 at 4 13 26 PM (2)](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/b3e70aa9-388f-4d9b-9d66-8544c759fbd6)
![WhatsApp Image 2023-11-14 at 4 13 27 PM (1)
![WhatsApp Image 2023-11-14 at 4 13 27 PM (2)](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/04176423-4633-41c3-810f-3f7759e47310)
](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/5a7830c9-3afb-4511-bf8e-cda51232bbba)
How to find  this model good or bad

**Comment by manisaranbala** [comment]
![WhatsApp Image 2023-11-14 at 4 13 27 PM (2)](https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/5b59ba2f-3a17-4233-8247-5d5486d12084)

**Comment by iliasam** [comment]
Again:
"Do you have this problem with USB-UART converter?
Also, try to disconnect RX line of U85B module - maybe 5V from Arduino is bad for U85B"

**Comment by manisaranbala** [comment]
https://github.com/iliasam/Laser_tape_reverse_engineering/assets/5657183/57c5d04f-e0e8-43cd-845b-881dcae52d1a

**Comment by manisaranbala** [comment]
Amplitude Reduse Automatically . That time  mismatched calculation . how to solve this problems?
