### ISSUE TITLE
Was this amazing project's code based on https://hackaday.io/project/189520-laser-range-finder ?

### ISSUE THREAD

**Issue by paaspaas00** [iliasam/Laser_tape_reverse_engineering#12]
Hi! 
Thanks for this project, that's an amazing learning resource!
I've noticed that the code here https://hackaday.io/project/189520-laser-range-finder in the image looks almost the same, is the project based on/inspired by that?

**Comment by iliasam** [comment]
Hello.  My project started in 2017, so Chinese project is newer.
