### ISSUE TITLE
Port it Arduino framework to make it portable

### ISSUE THREAD

**Issue by teaalltr** [iliasam/Laser_tape_reverse_engineering#13]
So it would be nice to port it to Arduino framework so people can easily tinker with the code. It can also allow for use with different chips like the esp32 etc.
There exist a port of the Arduino framework for the stm32 [here](https://github.com/stm32duino/Arduino_Core_STM32) which is supported and easy to use with platformio, vscode and Arduino ide. 

There are also Holtek chips that are almost clones of the stm32, and they provide a nice application note with code, PCB, schematics etc here https://www.holtek.com/page/applications/detail/WAS-18A1
It would be great to port your code to this chip too, especially since this application note is used by all sorts of Chinese rebranders to develop their cheap rangefinders and measurement devices.
The Arduino framework would make the porting process much easier for all these platforms.

Porting the code should be pretty straight-forward, just replace all stm32-specific library code with the more generic Arduino counterparts and make the pin config generic and maybe in another file.

**Comment by iliasam** [comment]
I don't want to do it. 
This project is really exotic (only a few people is interested in it, for most of people its easier to by module with factory UART enabled); Chinese make newer hardware to quick and reverse engineering is needed in any case. 
As I can see, different hardware can be used by rangefinder manufacturers  -  one or two lasers, HW is designed for different IF frequency, different HW constants.
Porting to a new HW is not just - "change pin definitions".
