### ISSUE TITLE
Lowering the baud rate

### ISSUE THREAD

**Issue by IDmedia** [iliasam/Laser_tape_reverse_engineering#2]
The laser works perfectly on a PC, but I have issues using it on my Wemos D1 Mini Pro. I have tried the TX/RX pins and SoftwareSerial, but I only get questionmarks and weird characters indicating that the baud rate is wrong.

I have found multiple people saying that SoftwareSerial doesn't play well beyond 115200. I found the definition of the baud rate in the firmware, but would it be possible to lowering it without any further concern? Any tips on how I can rebuild the firmware hex file?

**Comment by iliasam** [comment]
My firmware is based on that data transmission is high enough. If you try to decrease baudrate it can broke down TX process.
So the TX process in the firmware must be rewritten.
