### ISSUE TITLE
Request firmware with lower baudrate

### ISSUE THREAD

**Issue by MickTheMechanic** [iliasam/Laser_tape_reverse_engineering#7]
I would like to request a copy of firmware Firmware_dist_calculation_fast for U85 module, but with a lower baudrate of 115200. 

The reason for this is to eliminate data corruption due to high baudrate as a reason for the unplausible values mentioned in #5

**Comment by bdevijve** [comment]
Hi, +1 as 115200 is the max speed that can be used on Tasmota...

**Comment by bdevijve** [comment]
As I plan to connect this device to Tasmota and upload the distance to MQTT, I will need to lower the UART speed to 115200 at max; but probably to lower the measurement frequency to let's say 1Hz... I will try to make the change on the provided firmware on my own and tell you about the result...

**Comment by iliasam** [comment]
I have published FW for 115200 baudrate. I have not tested it, but I think that it should work. https://github.com/iliasam/Laser_tape_reverse_engineering/blob/master/Code/CortexM0/Firmware_dist_calculation_fast_boot_115200.hex

**Comment by iliasam** [comment]
Did someone tested new firmware?

**Comment by MickTheMechanic** [comment]
I hope to test on Sunday, I have been very busy the last days.

**Comment by MickTheMechanic** [comment]
Firmware is working well, thanks!
