### ISSUE TITLE
88B planned ?

### ISSUE THREAD

**Issue by skiphansen** [iliasam/Laser_tape_reverse_engineering#8]
Great project!  

Unfortunately the X-40's are very scarce  now.  I bought the only one I could find on ebay and it just arrived ... with an 88B module.  Any chance you're going to support it someday?  Any suggestions where I might find a X-40 with the right module?

Thanks for the amazing work in any case ... wish I could give you 4 stars!

Skip

**Comment by skiphansen** [comment]
I looks like the 88B module already has serial which is what I need.  But I can't find any documentation on the serial protocol, sigh.

Here's some info I mined from https://www.alibaba.com/product-detail/Phase-Shift-M88B-Laser-Distance-Measurement_60696810434.html
![serial_connections](https://user-images.githubusercontent.com/4642629/180901799-c201de75-052a-4883-b1ce-3f28b23435ba.png)
![pinout](https://user-images.githubusercontent.com/4642629/180901803-297508e4-fbf7-4b63-a10c-38aff8669183.png)

**Comment by iliasam** [comment]
Hello.
Unfortunately, support for M88 modules is not planned - I don't have such module.
Newer U85x modules are supported: [Link](https://github.com/iliasam/Laser_tape_reverse_engineering/wiki/U85-laser-rangefinder-modules)
Notice that firmware for cheap laser tape measure modules is differ from more expensive "UART" versions of that modules - UART is disabled in laser tape measures.
Looks like that this is manual for M88: [Link](https://forum.arduino.cc/uploads/short-url/hZh63mc9cPaRPq44QVSyfyYtYYF.pdf)

**Comment by skiphansen** [comment]
Thanks for the quick response! I wish shipping from China was as fast!
I'll order some U85x versions and revisit my project in a month or so.
